version: '3.7'
services:
  movie-service:
    container_name: movie-service
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    image: recruitment-task/movie-service
    ports:
      - published: ${MOVIE_PORT:-4000}
        target: 4000
    links:
      - mongo
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_TOKEN: ${OMDB_TOKEN}
      DB_CONNECTION: ${DB_CONNECTION}
    restart: unless-stopped
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: recruitment-task/auth-service
    ports:
      - published: ${AUTH_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped