version: '3.7'
services:
  app:
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - published: ${APP_PORT:-4000}
        target: 4000
    links:
      - mongo
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_TOKEN: ${OMDB_TOKEN}
      DB_CONNECTION: ${DB_CONNECTION}
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"