name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: create env file
        run: |
          touch .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo OMDB_TOKEN=${{ secrets.OMDB_TOKEN }} >> .env
          echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> .env

      - name: Run Tests
        run: docker-compose run --rm movie-service npm test
